CREATE TABLE IF NOT EXISTS users(
	id TEXT PRIMARY KEY NOT NULL UNIQUE,
	username TEXT NOT NULL UNIQUE,
	email TEXT NOT NULL UNIQUE,
	oauth_id TEXT NOT NULL UNIQUE,
	avatar TEXT NOT NULL UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

